/*
 * This file is generated by jOOQ.
 */
package com.nohibernate.demo.jooq.tables;


import com.nohibernate.demo.jooq.tables.Account;
import com.nohibernate.demo.jooq.tables.AccountToPolicy;
import com.nohibernate.demo.jooq.tables.Policy;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PK_ACCOUNT = Indexes0.PK_ACCOUNT;
    public static final Index ID = Indexes0.ID;
    public static final Index U_ACCOUNT_TO_POLICY = Indexes0.U_ACCOUNT_TO_POLICY;
    public static final Index PK_POLICY = Indexes0.PK_POLICY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PK_ACCOUNT = Internal.createIndex("pk_account", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ID }, true);
        public static Index ID = Internal.createIndex("id", AccountToPolicy.ACCOUNT_TO_POLICY, new OrderField[] { AccountToPolicy.ACCOUNT_TO_POLICY.ID }, true);
        public static Index U_ACCOUNT_TO_POLICY = Internal.createIndex("u_account_to_policy", AccountToPolicy.ACCOUNT_TO_POLICY, new OrderField[] { AccountToPolicy.ACCOUNT_TO_POLICY.POLICY_ID, AccountToPolicy.ACCOUNT_TO_POLICY.ACCOUNT_ID }, true);
        public static Index PK_POLICY = Internal.createIndex("pk_policy", Policy.POLICY, new OrderField[] { Policy.POLICY.ID }, true);
    }
}
