/*
 * This file is generated by jOOQ.
 */
package com.nohibernate.demo.jooq.tables;


import com.nohibernate.demo.jooq.tables.Account;
import com.nohibernate.demo.jooq.tables.AccountToPolicy;
import com.nohibernate.demo.jooq.tables.Policy;
import com.nohibernate.demo.jooq.tables.records.AccountRecord;
import com.nohibernate.demo.jooq.tables.records.AccountToPolicyRecord;
import com.nohibernate.demo.jooq.tables.records.PolicyRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountRecord, Long> IDENTITY_ACCOUNT = Identities0.IDENTITY_ACCOUNT;
    public static final Identity<AccountToPolicyRecord, Long> IDENTITY_ACCOUNT_TO_POLICY = Identities0.IDENTITY_ACCOUNT_TO_POLICY;
    public static final Identity<PolicyRecord, Long> IDENTITY_POLICY = Identities0.IDENTITY_POLICY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> PK_ACCOUNT = UniqueKeys0.PK_ACCOUNT;
    public static final UniqueKey<AccountToPolicyRecord> ID = UniqueKeys0.ID;
    public static final UniqueKey<AccountToPolicyRecord> U_ACCOUNT_TO_POLICY = UniqueKeys0.U_ACCOUNT_TO_POLICY;
    public static final UniqueKey<PolicyRecord> PK_POLICY = UniqueKeys0.PK_POLICY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountRecord, Long> IDENTITY_ACCOUNT = Internal.createIdentity(Account.ACCOUNT, Account.ACCOUNT.ID);
        public static Identity<AccountToPolicyRecord, Long> IDENTITY_ACCOUNT_TO_POLICY = Internal.createIdentity(AccountToPolicy.ACCOUNT_TO_POLICY, AccountToPolicy.ACCOUNT_TO_POLICY.ID);
        public static Identity<PolicyRecord, Long> IDENTITY_POLICY = Internal.createIdentity(Policy.POLICY, Policy.POLICY.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> PK_ACCOUNT = Internal.createUniqueKey(Account.ACCOUNT, "pk_account", Account.ACCOUNT.ID);
        public static final UniqueKey<AccountToPolicyRecord> ID = Internal.createUniqueKey(AccountToPolicy.ACCOUNT_TO_POLICY, "id", AccountToPolicy.ACCOUNT_TO_POLICY.ID);
        public static final UniqueKey<AccountToPolicyRecord> U_ACCOUNT_TO_POLICY = Internal.createUniqueKey(AccountToPolicy.ACCOUNT_TO_POLICY, "u_account_to_policy", AccountToPolicy.ACCOUNT_TO_POLICY.POLICY_ID, AccountToPolicy.ACCOUNT_TO_POLICY.ACCOUNT_ID);
        public static final UniqueKey<PolicyRecord> PK_POLICY = Internal.createUniqueKey(Policy.POLICY, "pk_policy", Policy.POLICY.ID);
    }
}
