/*
 * This file is generated by jOOQ.
 */
package com.nohibernate.demo.jooq.tables;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -381157040;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = com.nohibernate.demo.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>public.account_to_policy</code>.
     */
    public final AccountToPolicy ACCOUNT_TO_POLICY = com.nohibernate.demo.jooq.tables.AccountToPolicy.ACCOUNT_TO_POLICY;

    /**
     * The table <code>public.policy</code>.
     */
    public final Policy POLICY = com.nohibernate.demo.jooq.tables.Policy.POLICY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACCOUNT_ID_SEQ,
            Sequences.ACCOUNT_TO_POLICY_ID_SEQ,
            Sequences.POLICY_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            AccountToPolicy.ACCOUNT_TO_POLICY,
            Policy.POLICY);
    }
}
