/*
 * This file is generated by jOOQ.
 */
package com.nohibernate.demo.jooq.tables;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.account_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNT_ID_SEQ = new SequenceImpl<Long>("account_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.account_to_policy_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNT_TO_POLICY_ID_SEQ = new SequenceImpl<Long>("account_to_policy_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.policy_id_seq</code>
     */
    public static final Sequence<Long> POLICY_ID_SEQ = new SequenceImpl<Long>("policy_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
