/*
 * This file is generated by jOOQ.
 */
package com.nohibernate.demo.jooq.tables;


import com.nohibernate.demo.jooq.tables.Account;
import com.nohibernate.demo.jooq.tables.AccountToPolicy;
import com.nohibernate.demo.jooq.tables.Policy;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = com.nohibernate.demo.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>public.account_to_policy</code>.
     */
    public static final AccountToPolicy ACCOUNT_TO_POLICY = com.nohibernate.demo.jooq.tables.AccountToPolicy.ACCOUNT_TO_POLICY;

    /**
     * The table <code>public.policy</code>.
     */
    public static final Policy POLICY = com.nohibernate.demo.jooq.tables.Policy.POLICY;
}
