/*
 * This file is generated by jOOQ.
 */
package com.nohibernate.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountToPolicy implements Serializable {

    private static final long serialVersionUID = -2061233077;

    private final Long id;
    private final Long policyId;
    private final Long accountId;

    public AccountToPolicy(AccountToPolicy value) {
        this.id = value.id;
        this.policyId = value.policyId;
        this.accountId = value.accountId;
    }

    public AccountToPolicy(
        Long id,
        Long policyId,
        Long accountId
    ) {
        this.id = id;
        this.policyId = policyId;
        this.accountId = accountId;
    }

    public Long getId() {
        return this.id;
    }

    public Long getPolicyId() {
        return this.policyId;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountToPolicy (");

        sb.append(id);
        sb.append(", ").append(policyId);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
