/*
 * This file is generated by jOOQ.
 */
package com.nohibernate.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = -1280907804;

    private final Long   id;
    private final String accountNumber;

    public Account(Account value) {
        this.id = value.id;
        this.accountNumber = value.accountNumber;
    }

    public Account(
        Long   id,
        String accountNumber
    ) {
        this.id = id;
        this.accountNumber = accountNumber;
    }

    public Long getId() {
        return this.id;
    }

    public String getAccountNumber() {
        return this.accountNumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(accountNumber);

        sb.append(")");
        return sb.toString();
    }
}
