/*
 * This file is generated by jOOQ.
 */
package com.nohibernate.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Policy implements Serializable {

    private static final long serialVersionUID = -1641500438;

    private final Long   id;
    private final String policyNumber;

    public Policy(Policy value) {
        this.id = value.id;
        this.policyNumber = value.policyNumber;
    }

    public Policy(
        Long   id,
        String policyNumber
    ) {
        this.id = id;
        this.policyNumber = policyNumber;
    }

    public Long getId() {
        return this.id;
    }

    public String getPolicyNumber() {
        return this.policyNumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Policy (");

        sb.append(id);
        sb.append(", ").append(policyNumber);

        sb.append(")");
        return sb.toString();
    }
}
